#!/usr/bin/env bash
set -euo pipefail

BUNDLE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${BUNDLE_DIR}/.." && pwd)"

MODEL_DIR="${MODEL_DIR:-/mnt/sfs_turbo/models/Qwen3.5-4B}"
HOST="${HOST:-127.0.0.1}"
PORT="${PORT:-8000}"
TENSOR_PARALLEL_SIZE="${TENSOR_PARALLEL_SIZE:-4}"
MM_PROCESSOR_CACHE_TYPE="${MM_PROCESSOR_CACHE_TYPE:-shm}"
MM_PROCESSOR_CACHE_GB="${MM_PROCESSOR_CACHE_GB:-20}"
MM_ENCODER_TP_MODE="${MM_ENCODER_TP_MODE:-data}"
GPU_MEMORY_UTILIZATION="${GPU_MEMORY_UTILIZATION:-0.85}"
MAX_MODEL_LEN="${MAX_MODEL_LEN:-36864}"
ALLOWED_LOCAL_MEDIA_PATH="${ALLOWED_LOCAL_MEDIA_PATH:-${ROOT_DIR}/data}"
ENABLE_PERF_PROBE="${ENABLE_PERF_PROBE:-1}"
ENABLE_ASYNC_SCHEDULING="${ENABLE_ASYNC_SCHEDULING:-1}"
ENABLE_CPU_BINDING="${ENABLE_CPU_BINDING:-true}"

export ORIG_PYTHONPATH="${PYTHONPATH:-}"
export HOME="${HOME:-/tmp/vllm-home}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-${HOME}/.config}"
export TRITON_CACHE_DIR="${TRITON_CACHE_DIR:-/tmp/triton-cache}"
export HCCL_BUFFSIZE="${HCCL_BUFFSIZE:-1024}"
export VLLM_ASCEND_ENABLE_PREFETCH_MLP="${VLLM_ASCEND_ENABLE_PREFETCH_MLP:-1}"
export HCCL_OP_EXPANSION_MODE="${HCCL_OP_EXPANSION_MODE:-AIV}"
export CPU_AFFINITY_CONF="${CPU_AFFINITY_CONF:-1}"
export VLLM_USE_V1="${VLLM_USE_V1:-1}"
export PYTORCH_NPU_ALLOC_CONF="${PYTORCH_NPU_ALLOC_CONF:-expandable_segments:True}"
export VLLM_ASCEND_MM_FILE_MAP="${VLLM_ASCEND_MM_FILE_MAP:-/tmp/vllm_ascend_mm_file_map.jsonl}"
export VLLM_ASCEND_PHASE2_VALIDATE_FILE="${VLLM_ASCEND_PHASE2_VALIDATE_FILE:-/tmp/vllm_ascend_phase2_validate.jsonl}"
export VLLM_ASCEND_PERF_PROBE="${VLLM_ASCEND_PERF_PROBE:-${ENABLE_PERF_PROBE}}"
export VLLM_ASCEND_PERF_PROBE_FILE="${VLLM_ASCEND_PERF_PROBE_FILE:-/tmp/vllm_ascend_perf_probe.jsonl}"
export VLLM_PLUGINS="${VLLM_PLUGINS:-phase2_local_plugin,ascend}"
export PYTHONPATH="${BUNDLE_DIR}:${ADDITIONAL_PYTHONPATH:-}:${ORIG_PYTHONPATH}"
export MODEL_DIR HOST PORT
export TENSOR_PARALLEL_SIZE MM_PROCESSOR_CACHE_TYPE MM_PROCESSOR_CACHE_GB
export MM_ENCODER_TP_MODE GPU_MEMORY_UTILIZATION MAX_MODEL_LEN
export ALLOWED_LOCAL_MEDIA_PATH ENABLE_CPU_BINDING

mkdir -p "${XDG_CONFIG_HOME}" "${TRITON_CACHE_DIR}"
: > "${VLLM_ASCEND_MM_FILE_MAP}"
: > "${VLLM_ASCEND_PHASE2_VALIDATE_FILE}"

if [[ "${ENABLE_ASYNC_SCHEDULING}" != "1" ]]; then
  export ENABLE_ASYNC_SCHEDULING=0
fi

exec python -u "${ROOT_DIR}/scripts/launch_registered_server.py"
